"""add_relationship_table

Revision ID: 49e7713da53a
Revises: ad44940fd57c
Create Date: 2026-05-12 11:37:15.671608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e7713da53a'
down_revision: Union[str, None] = 'ad44940fd57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=100), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_given', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'counterparty_name', name='uq_user_counterparty_name')
    )
    op.create_index('ix_relationships_user_id', 'relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationships_user_id', table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
