"""add_email_verification

Revision ID: b2e422fc78b3
Revises: a7dde9049673
Create Date: 2026-05-18 13:43:04.618281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e422fc78b3'
down_revision: Union[str, None] = 'a7dde9049673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=255), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verify_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
